"""Week 4 - Logical planning: STRIPS-style BFS planner for the warehouse robot.

Provenance (see report): the Action / applicable / apply / bfs structure was
generated by an LLM (Claude) from the Task 2 prompt.  Modifications made during
review: (1) an independent validate_plan() that does not share code with bfs(),
(2) a negative precondition ~Holding on PickUp, (3) the test suite.
"""
from collections import deque
from dataclasses import dataclass


@dataclass(frozen=True)
class Action:
    name: str
    pos_pre: frozenset = frozenset()
    neg_pre: frozenset = frozenset()
    pos_eff: frozenset = frozenset()
    neg_eff: frozenset = frozenset()


def act(name, pos_pre=(), neg_pre=(), pos_eff=(), neg_eff=()):
    return Action(name, frozenset(pos_pre), frozenset(neg_pre),
                  frozenset(pos_eff), frozenset(neg_eff))


def applicable(state, a):
    """S |= Preconditions(a): all positive preconds in S, no negative precond in S."""
    return a.pos_pre <= state and not (a.neg_pre & state)


def apply_action(state, a):
    """Remove negative effects, then add positive effects."""
    return (state - a.neg_eff) | a.pos_eff


def bfs_plan(init, goal, actions):
    """Return (plan, states) or None.  plan = list of Action, states = S0..Sn."""
    init = frozenset(init)
    goal = frozenset(goal)
    if goal <= init:
        return [], [init]
    frontier = deque([(init, [], [init])])
    visited = {init}
    while frontier:
        state, plan, states = frontier.popleft()
        for a in actions:
            if not applicable(state, a):
                continue
            nxt = apply_action(state, a)
            if nxt in visited:
                continue
            visited.add(nxt)
            if goal <= nxt:
                return plan + [a], states + [nxt]
            frontier.append((nxt, plan + [a], states + [nxt]))
    return None


def validate_plan(init, goal, plan):
    """Independent check: replay the plan, verifying every precondition
    explicitly, then verify the goal.  Returns (ok, log)."""
    state = set(init)
    log = []
    for i, a in enumerate(plan, 1):
        missing = [p for p in sorted(a.pos_pre) if p not in state]
        violated = [p for p in sorted(a.neg_pre) if p in state]
        if missing or violated:
            log.append(f"step {i} {a.name}: INVALID (missing {missing}, "
                       f"forbidden-but-present {violated})")
            return False, log
        for p in a.neg_eff:
            state.discard(p)
        for p in a.pos_eff:
            state.add(p)
        log.append(f"step {i} {a.name}: preconditions OK")
    ok = set(goal) <= state
    log.append("goal satisfied" if ok else f"goal NOT satisfied, missing {sorted(set(goal) - state)}")
    return ok, log


# ---------------------------------------------------------------- warehouse
EDGES = [("A", "B"), ("B", "A"), ("B", "C"), ("C", "B")]
LOCS = ["A", "B", "C"]


def move(x, y):
    return act(f"Move({x},{y})", pos_pre=[f"At(Robot,{x})"],
               pos_eff=[f"At(Robot,{y})"], neg_eff=[f"At(Robot,{x})"])


def pickup(l):
    return act(f"PickUp(Package,{l})",
               pos_pre=[f"At(Robot,{l})", f"At(Package,{l})"],
               neg_pre=["Holding(Package)"],
               pos_eff=["Holding(Package)"], neg_eff=[f"At(Package,{l})"])


def drop(l):
    return act(f"Drop(Package,{l})",
               pos_pre=[f"At(Robot,{l})", "Holding(Package)"],
               pos_eff=[f"At(Package,{l})"], neg_eff=["Holding(Package)"])


MOVES = [move(x, y) for x, y in EDGES]
PICKS = [pickup(l) for l in LOCS]
DROPS = [drop(l) for l in LOCS]
ALL_ACTIONS = MOVES + PICKS + DROPS
INIT = {"At(Robot,A)", "At(Package,A)"}
GOAL = {"At(Package,C)"}


def fmt(s):
    return "{" + ", ".join(sorted(s)) + "}"


def report(title, init, goal, actions, expect_plan):
    print(f"\n=== {title} ===")
    print("Initial:", fmt(init))
    print("Goal:   ", fmt(goal))
    print("Actions:", ", ".join(a.name for a in actions))
    res = bfs_plan(init, goal, actions)
    if res is None:
        print("Result: No plan found")
        found, valid = False, None
    else:
        plan, states = res
        found = True
        print(f"Result: plan of length {len(plan)}: " +
              (" -> ".join(a.name for a in plan) or "(empty)"))
        for i, s in enumerate(states):
            label = "S0" if i == 0 else f"S{i} after {plan[i-1].name}"
            print(f"  {label}: {fmt(s)}")
        valid, log = validate_plan(init, goal, plan)
        for line in log:
            print("  [validator]", line)
        print("Plan valid:", valid)
    assert found == expect_plan, f"{title}: expected found={expect_plan}"
    if found:
        assert valid
    return found, valid


def main():
    print("Task 0: applicability in the initial state")
    for a in (pickup("A"), drop("C")):
        print(f"  {a.name}: applicable = {applicable(frozenset(INIT), a)}")

    report("Test A: solvable warehouse problem", INIT, GOAL, ALL_ACTIONS, True)

    report("Test B: impossible (PickUp removed)", INIT, GOAL, MOVES + DROPS, False)

    # Test C: robot reaching C is not the same as the package reaching C.
    report("Test C1: only Moves available, goal At(Package,C)", INIT, GOAL, MOVES, False)
    report("Test C2: only Moves available, goal At(Robot,C)", INIT, {"At(Robot,C)"}, MOVES, True)
    shortcut = act("Teleport(Robot,A,C)", pos_pre=["At(Robot,A)"],
                   pos_eff=["At(Robot,C)"], neg_eff=["At(Robot,A)"])
    report("Test C3: extra robot-only shortcut action added, goal At(Package,C)",
           INIT, GOAL, ALL_ACTIONS + [shortcut], True)

    # Extra checks
    print("\n=== Extra: validator rejects an invalid plan ===")
    bad = [move("A", "B"), move("B", "C"), drop("C")]  # never picked up
    ok, log = validate_plan(INIT, GOAL, bad)
    for line in log:
        print("  [validator]", line)
    assert not ok
    print("Extra: 'looks reasonable' plan rejected ->", not ok)

    print("\n=== Extra: negative precondition blocks an action ===")
    # Artificial state: PickUp's positive preconditions hold, but the robot is already holding.
    held = frozenset({"At(Robot,A)", "At(Package,A)", "Holding(Package)"})
    a = pickup("A")
    print("  State:", fmt(held))
    print(f"  {a.name}: positive preconditions hold = {a.pos_pre <= held}, applicable = {applicable(held, a)}")
    assert a.pos_pre <= held and not applicable(held, a)
    ok, log = validate_plan(held, {"Holding(Package)"}, [a])
    for line in log:
        print("  [validator]", line)
    assert not ok

    print("\n=== Extra: goal already satisfied ===")
    res = bfs_plan(INIT, {"At(Package,A)"}, ALL_ACTIONS)
    print("  plan length:", len(res[0]))
    assert res[0] == []

    print("\nAll tests passed.")


if __name__ == "__main__":
    main()
